### ISSUE TITLE
Add an API to stream events as they happen for discovery

### ISSUE THREAD

**Issue by josevalim** [beam-telemetry/telemetry#12]
It would be nice if we had an API that collected/logged all events published in a certain time period. This would make it easy to discover events. For example, in a Phoenix application I could say: call `IO.inspect/1` for all events in the next 5 seconds.

I am not sure if this functionality belongs here. In order to not slow down telemetry, we could implement this using :erlang.trace. The goal here is debugging, so it is important to not slow down the main telemetry engine. We could also add this to telemetry_sampler.

**Comment by cloud8421** [comment]
Good idea, I would personally prefer the second option you mentioned (adding it to `telemetry_sampler`) so that it can evolve indipendently (which as a side effect it can prove the concept of small, stable core and extensions built on top).

**Comment by bryannaegele** [comment]
We've discussed a number of ways to discover telemetry events for a variety of use cases, most recently as it pertains to registering of event handlers for tracing purposes. Knowledge of event names is a predicate to registering handlers, so we are left with two potential avenues: compile-time introspection or explicit declaration.

Note that this is not intended to be the sole mechanism for event discovery, but I believe it provides a lot of functionality we're looking for in an unintrusive way.

### Compile-time Introspection

This is arguably the best overall solution since it requires no additional steps by the user. In my initial investigation, introspection would be difficult to achieve, especially across languages.

### Explicit Declaration

By requiring the user or library author to explicitly declare possible events, we have a straightforward mechanism to make use of that declaration at various steps and with a broad range of applications.

#### Behaviour

One option would be to provide a behaviour with a `telemetry_events/0` function which returns a list of discoverable events.

#### Module Attribute

Introduce an attribute of `telemetry_events` with a list of discoverable events.

Each of the above is easily discoverable at runtime and compile-time. My initial idea was to use module attributes but, after further consideration, I'm leaning towards @josevalim's idea of going with a behaviour. It's just as easy to use for a user, feels more idiomatic, and provides flexibility going forward. It's probably more useful from a tooling perspective, as well.

### Proposal

- [ ] Introduce a `telemetry` behaviour with a `telemetry_events/0` callback (default impl returns `[]`).
- [ ] Expand the API to add `telemetry:register_event/1`, `telemetry:deregister_event/1`, and `telemetry:register_all_events/1` functions to support further runtime declaration flexibility and discoverability (ETS storage is probably fine).
  - [ ] Fire events for invocation of each of the above which a tracing or other interested library could listen for.
  - [ ] Validate event name declarations during registration.
  - [ ] Validate against duplicate event names. (Raise an exception? This situation is likely to cause handler detachments. We should at least warn.)
  - [ ] Store registering module names with the event name? This could be useful in debugging or warning against duplicate event names being registered from different namespaces.
- [ ] Add `telemetry:list_all_events/0` would return all registered events.

/cc @arkgil @GregMefford @tsloughter @hauleth @binaryseed

**Comment by josevalim** [comment]
@bryannaegele thanks for the summary. I have moved your discussion to a separate issue because I think we should distinguish between the two types of discovery: this one is about emitting them as they happen .Your proposal is about discovering them upfront. :)

**Comment by bryannaegele** [comment]
Closing since this would be available via the registry.
